/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AdminAuthorized: typeof import('./components/AdminAuthorized.vue')['default']
    AudioToAssets: typeof import('./components/AudioToAssets.vue')['default']
    BDAudioConversation: typeof import('./components/BDAudioConversation.vue')['default']
    BDModulosDropzones: typeof import('./components/BDModulosDropzones.vue')['default']
    BDModulosInputs: typeof import('./components/BDModulosInputs.vue')['default']
    BDModulosSaveTemplate: typeof import('./components/BDModulosSaveTemplate.vue')['default']
    BDModulosTemplates: typeof import('./components/BDModulosTemplates.vue')['default']
    BuilderDetails: typeof import('./components/builderDetails.vue')['default']
    BuilderDetailsAssets: typeof import('./components/builderDetailsAssets.vue')['default']
    BuilderDetailsAssetsList: typeof import('./components/builderDetailsAssetsList.vue')['default']
    BuilderDetailsAssetsUploader: typeof import('./components/builderDetailsAssetsUploader.vue')['default']
    BuilderDetailsAudios: typeof import('./components/builderDetailsAudios.vue')['default']
    BuilderDetailsBlocks: typeof import('./components/builderDetailsBlocks.vue')['default']
    BuilderDetailsCodigo: typeof import('./components/builderDetailsCodigo.vue')['default']
    BuilderDetailsContainers: typeof import('./components/builderDetailsContainers.vue')['default']
    BuilderDetailsContainersDraggable: typeof import('./components/builderDetailsContainersDraggable.vue')['default']
    BuilderDetailsModulos: typeof import('./components/builderDetailsModulos.vue')['default']
    BuilderDetailsModulosNested: typeof import('./components/builderDetailsModulosNested.vue')['default']
    BuilderDetailsPrompts: typeof import('./components/builderDetailsPrompts.vue')['default']
    BuilderDocManager: typeof import('./components/BuilderDocManager.vue')['default']
    BuilderMain: typeof import('./components/builderMain.vue')['default']
    BuilderMenu: typeof import('./components/builderMenu.vue')['default']
    BuilderNotes: typeof import('./components/builderNotes.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
    UserAdmin: typeof import('./components/UserAdmin.vue')['default']
    UserAuth: typeof import('./components/UserAuth.vue')['default']
    UserLogout: typeof import('./components/UserLogout.vue')['default']
  }
}
