/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    A11Conversation: typeof import('./components/audios11labs/a11Conversation.vue')['default']
    A11FilterVoices: typeof import('./components/audios11labs/a11FilterVoices.vue')['default']
    A11LoadVoices: typeof import('./components/audios11labs/a11LoadVoices.vue')['default']
    AdminAuthorized: typeof import('./components/AdminAuthorized.vue')['default']
    AudioToAssets: typeof import('./components/AudioToAssets.vue')['default']
    AudioToFile: typeof import('./components/AudioToFile.vue')['default']
    BDAssistant: typeof import('./components/BDAssistant.vue')['default']
    BDAudioConversation: typeof import('./components/BDAudioConversation.vue')['default']
    BDAudioConversationManual: typeof import('./components/BDAudioConversationManual.vue')['default']
    BDMIBlob: typeof import('./components/BDMIBlob.vue')['default']
    BDMInputsDescription: typeof import('./components/BDMInputsDescription.vue')['default']
    BDModulosDropzones: typeof import('./components/BDModulosDropzones.vue')['default']
    BDModulosInputs: typeof import('./components/BDModulosInputs.vue')['default']
    BDModulosInputsRepeater: typeof import('./components/BDModulosInputsRepeater.vue')['default']
    BDModulosSaveTemplate: typeof import('./components/BDModulosSaveTemplate.vue')['default']
    BDModulosTemplates: typeof import('./components/BDModulosTemplates.vue')['default']
    BuilderDetails: typeof import('./components/builderDetails.vue')['default']
    BuilderDetailsAssets: typeof import('./components/builderDetailsAssets.vue')['default']
    BuilderDetailsAssetsList: typeof import('./components/builderDetailsAssetsList.vue')['default']
    BuilderDetailsAssetsUploader: typeof import('./components/builderDetailsAssetsUploader.vue')['default']
    BuilderDetailsAudios: typeof import('./components/builderDetailsAudios.vue')['default']
    BuilderDetailsAudiosEleven: typeof import('./components/builderDetailsAudiosEleven.vue')['default']
    BuilderDetailsBlocks: typeof import('./components/builderDetailsBlocks.vue')['default']
    BuilderDetailsCodigo: typeof import('./components/builderDetailsCodigo.vue')['default']
    BuilderDetailsContainers: typeof import('./components/builderDetailsContainers.vue')['default']
    BuilderDetailsContainersDraggable: typeof import('./components/builderDetailsContainersDraggable.vue')['default']
    BuilderDetailsModulos: typeof import('./components/builderDetailsModulos.vue')['default']
    BuilderDetailsModulosNested: typeof import('./components/builderDetailsModulosNested.vue')['default']
    BuilderDetailsPrompts: typeof import('./components/builderDetailsPrompts.vue')['default']
    BuilderDocManager: typeof import('./components/BuilderDocManager.vue')['default']
    BuilderMain: typeof import('./components/builderMain.vue')['default']
    BuilderMenu: typeof import('./components/builderMenu.vue')['default']
    BuilderNotes: typeof import('./components/builderNotes.vue')['default']
    LoadVoices: typeof import('./components/audios11labs/loadVoices.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Rt1: typeof import('./components/riodastest/rt1.vue')['default']
    Rt2: typeof import('./components/riodastest/rt2.vue')['default']
    Rt3: typeof import('./components/riodastest/rt3.vue')['default']
    Rt6: typeof import('./components/riodastest/rt6.vue')['default']
    Rt7: typeof import('./components/riodastest/rt7.vue')['default']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
    UserAdmin: typeof import('./components/UserAdmin.vue')['default']
    UserAuth: typeof import('./components/UserAuth.vue')['default']
    UserLogout: typeof import('./components/UserLogout.vue')['default']
  }
}
